# Generated by Django 2.0.8 on 2019-02-24 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190217_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dd',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default='reborn', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
